/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-17 06:20:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/view/layout/import.jsp", Long.valueOf(1587052391539L));
    _jspx_dependants.put("/view/layout/footer.jsp", Long.valueOf(1587052391146L));
    _jspx_dependants.put("/view/layout/Header.jsp", Long.valueOf(1587103480562L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\"> -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css\"> \r\n");
      out.write("<!-- 위에 삭제 해보기 -->\r\n");
      out.write("\r\n");
      out.write("<link type=\"text/css\" href=\"/Watch_Next/Resources/css/hedaer_footer.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link type=\"text/css\" href=\"/Watch_Next/Resources/css/hedaer_footer(AFTER).css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!--페이지에 적용되는 css넣기 -->\r\n");
      out.write("<link rel= \"stylesheet\" type=\"text/css\" href=\"/Watch_Next/Resources/css/a_tag.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("\n");
      out.write("<link type=\"text/css\" href=\"/Watch_Next/Resources/css/login.css\" rel=\"stylesheet\"/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!--header -->\n");
      out.write('\r');
      out.write('\n');

	Member loginUser = (Member)session.getAttribute("loginUser"); 

      out.write("\r\n");
      out.write("<!-- 헤더 -->\r\n");
      out.write("<header>\r\n");
      out.write("\t<div class=\"nav\">\r\n");
      out.write("\t\t<div class=\"navi_set\">\r\n");
      out.write("\t\t\t<div class=\"topnav\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\"><img id=\"logo\" src=\"/Watch_Next/Resources/images/logo.png\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"navi_set\"> \r\n");
      out.write("\t\t\t<div class=\"topnav\">영화</div>\r\n");
      out.write("\t\t\t<ul class=\"subnav\">\r\n");
      out.write("\t\t\t\t<li onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/movie.all'\">정보</li>\r\n");
      out.write("\t\t\t\t<li onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/rec_board.me'\">추천</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"navi_set\">\r\n");
      out.write("\t\t\t<div class=\"topnav\">게시판</div>\r\n");
      out.write("\t\t\t<ul class=\"subnav\">\r\n");
      out.write("\t\t\t\t<li onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/list.rv'\">리뷰 게시판</li>\r\n");
      out.write("\t\t\t\t<li onclick=\"goR();\">모집 게시판</li>\r\n");
      out.write("\t\t\t\t<li>창작 게시판</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"navi_set\">\r\n");
      out.write("\t\t\t<div class=\"topnav\">펀딩</div>\r\n");
      out.write("\t\t\t<ul class=\"subnav\">\r\n");
      out.write("\t\t\t\t<li>수요조사</li>\r\n");
      out.write("\t\t\t\t<li>펀딩참여</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"nav2\">\r\n");
      out.write("\t\t<form autocomplete=\"off\" method=\"post\" id=\"header_action\">\r\n");
      out.write("\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t<div class=\"container-4\">\r\n");
      out.write("\t\t\t\t\t<input type=\"search\" name=\"search\" id=\"search\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"검색어를 입력하세요..\" />\r\n");
      out.write("\t\t\t\t\t<button class=\"icon\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-search\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
 if(loginUser == null) {
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"topnav2\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/Watch_Next/view/pages/loginForm.jsp\" class=\"a_tag\">로그인</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"topnav2\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/Watch_Next/view/pages/JoinForm.jsp\" class=\"a_tag\">회원가입</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t");
 if(loginUser.getAdminYN().equals("N")){
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"topnav2\" id=\"myPage\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/list.all'\">마이 페이지</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
 }else {
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"topnav2\" id=\"myPage\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/view/admin/Admin_myPage.jsp'\">마이 페이지</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"topnav2\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/logout.me'\">로그아웃</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('.icon').click(function(){\r\n");
      out.write("\t\t\t$(\"#header_action\").attr(\"action\", \"");
      out.print(request.getContextPath());
      out.write("/search.mo?movieTitle=\" + $(\"#search\").val());\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goR(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/list.recruit\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<br clear=\"all\">\r\n");
      out.write('\n');

   String msg = (String)request.getAttribute("msg"); 
//    System.out.println("qkqh" + msg);

      out.write("\n");
      out.write("\n");
      out.write("<section>\n");
      out.write("\n");
      out.write("   <div id=\"lg_table\">\n");
      out.write("   <h2>로그인</h2>\n");
      out.write("   <hr class=\"hline\">\n");
      out.write("      <form class=\"lg_form\" onsubmit=\"return validate();\" action=\"");
      out.print( request.getContextPath() );
      out.write("/login.me\" method=\"post\">\n");
      out.write("         <div class=\"lg\">\n");
      out.write("            <div class=\"div\">\n");
      out.write("               <input type=\"text\" class=\"lg_text\" id=\"userId\"  name=\"userId\" placeholder=\"아이디\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"div\">\n");
      out.write("               <input type=\"password\" class=\"lg_text1\" id=\"userPwd\" name=\"userPwd\" placeholder=\"비밀번호\">\n");
      out.write("            </div>\n");
      out.write("         <div>\n");
      out.write("            <input type=\"submit\"  class=\"lg_button1\" value=\"로그인\">\n");
      out.write("         </div>\n");
      out.write("            <button type=\"button\" class=\"lg_button\" onclick=\"location='/Watch_Next/view/pages/JoinForm.jsp'\">회원가입</button>\n");
      out.write("            <button type=\"button\" class=\"lg_button\" id=\"find_member\" onclick=\"location='/Watch_Next/view/pages/FindUserForm.jsp'\" >아이디/비밀번호 찾기</button>\n");
      out.write("         </div>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- footer -->\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br clear=\"all\">\r\n");
      out.write("\r\n");
      out.write("<footer id=\"footer\">\r\n");
      out.write("\t<hr class=\"footer-line\">\r\n");
      out.write("\t<span class=\"f_bottom-contents\">회사소개</span> \r\n");
      out.write("\t<span class=\"f_bottom-contents\"> | 서비스 이용 약관</span>\r\n");
      out.write("\t<span class=\"f_bottom-contents\"> | 개인정보처리방침</span><br> \r\n");
      out.write("\t<img src=\"/Watch_Next/Resources/images/logo.png\" id=\"f_logo\">\r\n");
      out.write("\t<div id=\"copyright\">Copyright 2020. watchnext?. All rights reserved</div>\r\n");
      out.write("</footer>");
      out.write("\n");
      out.write("<script>\n");
      out.write("   function validate(){\n");
      out.write("      if($('#userId').val().trim().length == 0){\n");
      out.write("         alert('아이디를 입력해주세요');\n");
      out.write("         $('#userId').focus();\n");
      out.write("         return false;\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("      if($('#userPwd').val().trim().length == 0){\n");
      out.write("         alert('비밀번호를 입력해주세요');\n");
      out.write("         $('#userPwd').focus();\n");
      out.write("         \n");
      out.write("         return false;\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("      return true;\n");
      out.write("   }\n");
      out.write("   $(function(){\n");
      out.write("      var msg = '");
      out.print( msg );
      out.write("';\n");
      out.write("      if(msg.trim() == '이메일로 회원님의 정보를 보냈습니다. 확인 후 다시 로그인 해주세요.'){\n");
      out.write("         alert(msg)\n");
      out.write("      }\n");
      out.write("      if(msg.trim() == \"없는 회원입니다 다시 확인해주세요.\"){\n");
      out.write("         alert(msg)\n");
      out.write("      }\n");
      out.write("   })\n");
      out.write("   \n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<script src=\"/Watch_Next/Resources/js/Header.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
