/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-17 06:20:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.recruit;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import recruit.model.vo.*;
import member.model.vo.Member;

public final class recruitList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/view/layout/import.jsp", Long.valueOf(1587052391539L));
    _jspx_dependants.put("/view/layout/footer.jsp", Long.valueOf(1587052391146L));
    _jspx_dependants.put("/view/layout/Header.jsp", Long.valueOf(1587103480562L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("recruit.model.vo");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	ArrayList<Recruit> list = (ArrayList<Recruit>)request.getAttribute("list");
	PageInfo pi = (PageInfo)request.getAttribute("pi");
	ArrayList<Recruit> cList = (ArrayList<Recruit>)request.getAttribute("cList");
	
	int currentPage = pi.getCurrentPage();
	int maxPage = pi.getMaxPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage(); 
	

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>insert title</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\"> -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css\"> \r\n");
      out.write("<!-- 위에 삭제 해보기 -->\r\n");
      out.write("\r\n");
      out.write("<link type=\"text/css\" href=\"/Watch_Next/Resources/css/hedaer_footer.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link type=\"text/css\" href=\"/Watch_Next/Resources/css/hedaer_footer(AFTER).css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!--페이지에 적용되는 css넣기 -->\r\n");
      out.write("<link rel= \"stylesheet\" type=\"text/css\" href=\"/Watch_Next/Resources/css/a_tag.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\"> -->\r\n");
      out.write("<link type=\"text/css\" href=\"/Watch_Next/Resources/css/recruit_list.css\" rel=\"stylesheet\" >\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

	Member loginUser = (Member)session.getAttribute("loginUser"); 

      out.write("\r\n");
      out.write("<!-- 헤더 -->\r\n");
      out.write("<header>\r\n");
      out.write("\t<div class=\"nav\">\r\n");
      out.write("\t\t<div class=\"navi_set\">\r\n");
      out.write("\t\t\t<div class=\"topnav\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\"><img id=\"logo\" src=\"/Watch_Next/Resources/images/logo.png\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"navi_set\"> \r\n");
      out.write("\t\t\t<div class=\"topnav\">영화</div>\r\n");
      out.write("\t\t\t<ul class=\"subnav\">\r\n");
      out.write("\t\t\t\t<li onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/movie.all'\">정보</li>\r\n");
      out.write("\t\t\t\t<li onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/rec_board.me'\">추천</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"navi_set\">\r\n");
      out.write("\t\t\t<div class=\"topnav\">게시판</div>\r\n");
      out.write("\t\t\t<ul class=\"subnav\">\r\n");
      out.write("\t\t\t\t<li onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/list.rv'\">리뷰 게시판</li>\r\n");
      out.write("\t\t\t\t<li onclick=\"goR();\">모집 게시판</li>\r\n");
      out.write("\t\t\t\t<li>창작 게시판</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"navi_set\">\r\n");
      out.write("\t\t\t<div class=\"topnav\">펀딩</div>\r\n");
      out.write("\t\t\t<ul class=\"subnav\">\r\n");
      out.write("\t\t\t\t<li>수요조사</li>\r\n");
      out.write("\t\t\t\t<li>펀딩참여</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"nav2\">\r\n");
      out.write("\t\t<form autocomplete=\"off\" method=\"post\" id=\"header_action\">\r\n");
      out.write("\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t<div class=\"container-4\">\r\n");
      out.write("\t\t\t\t\t<input type=\"search\" name=\"search\" id=\"search\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"검색어를 입력하세요..\" />\r\n");
      out.write("\t\t\t\t\t<button class=\"icon\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-search\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
 if(loginUser == null) {
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"topnav2\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/Watch_Next/view/pages/loginForm.jsp\" class=\"a_tag\">로그인</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"topnav2\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/Watch_Next/view/pages/JoinForm.jsp\" class=\"a_tag\">회원가입</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t");
 if(loginUser.getAdminYN().equals("N")){
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"topnav2\" id=\"myPage\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/list.all'\">마이 페이지</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
 }else {
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"topnav2\" id=\"myPage\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/view/admin/Admin_myPage.jsp'\">마이 페이지</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"topnav2\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/logout.me'\">로그아웃</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('.icon').click(function(){\r\n");
      out.write("\t\t\t$(\"#header_action\").attr(\"action\", \"");
      out.print(request.getContextPath());
      out.write("/search.mo?movieTitle=\" + $(\"#search\").val());\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goR(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/list.recruit\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<br clear=\"all\">\r\n");
      out.write("\r\n");
      out.write("\t<br clear=\"all\">\r\n");
      out.write("\t\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- 모집 게시판 목록 -->\r\n");
      out.write("\t<br clear=\"all\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"recruit\">\r\n");
      out.write("\t\t<h2><strong>모집 게시판</strong></h2>\r\n");
      out.write("\t\t\t<hr class=\"hline\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th id=\"num\">번호</th>\r\n");
      out.write("\t\t\t\t<th id=\"rccategory\">말머리</th>\r\n");
      out.write("\t\t\t\t<th id=\"title\">글 제목</th>\r\n");
      out.write("\t\t\t\t<th id=\"date\">날짜</th>\r\n");
      out.write("\t\t\t\t<th id=\"writer\">글쓴이</th>\r\n");
      out.write("\t\t\t\t<th id=\"hits\">조회</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t");
 if(list.isEmpty()) { 
      out.write("\r\n");
      out.write("\t\t\t\t<td colspan=\"6\">조회된 리스트가 없습니다.</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t");
 for(Recruit r : list) { 
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(r.getrNo() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(r.getrHead() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(r.getbTitle() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(r.getbDate() );
      out.write("</td>\t\r\n");
      out.write("\t\t\t\t<td>");
      out.print(r.getUserId() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(r.getbViews() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write(" \r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<br><br><br><br>\r\n");
      out.write("\t<!-- 페이징 -->\r\n");
      out.write("\t\t<div class=\"list_number\" align=\"center\">\r\n");
      out.write("\t\t");
 if(!list.isEmpty()){ 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!-- 맨 처음으로 -->\r\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/list.recruit?currentPage=1'\"> &gt;</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 이전 페이지 -->\r\n");
      out.write("\t\t\t<button onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/list.recruit?currentPage=");
      out.print( currentPage - 1 );
      out.write("'\" id=\"before\">&gt;</button>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tif(");
      out.print( currentPage );
      out.write(" <=1){\r\n");
      out.write("\t\t\t\t\t\t$('#before').attr('disable', 'true');\r\n");
      out.write("\t\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!-- 10개 페이지 목록 -->\r\n");
      out.write("\t\t\t\t");
 for(int p = startPage; p <= endPage; p++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
 if(p == currentPage){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button id=\"ch\" disabled>");
      out.print( p );
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button id=\"num\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/list.recruit?currentPage=");
      out.print(p );
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<!-- 다음 페이지로 -->\r\n");
      out.write("\t\t\t\t<button id=\"after\" onclick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/list.recruit?currenPage=");
      out.print( currentPage + 1 );
      out.write("'\">&gt;</button>\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\tif(");
      out.print( currentPage );
      out.write(" >= ");
      out.print( maxPage );
      out.write("){\r\n");
      out.write("\t\t\t\t\t\t\t$('#after').attr('disable', 'true');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 맨 끝으로 -->\r\n");
      out.write("\t\t\t\t<button onclick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/list.recruit?currentPage=");
      out.print( maxPage );
      out.write("'\">&gt;&gt;</button>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t   \r\n");
      out.write("\t\t   \t\t<div class=\"search\" align=\"right\">\r\n");
      out.write("\t\t   \t\t\t ");
 if(loginUser != null){ 
      out.write(" \r\n");
      out.write("\t\t   \t\t\t\t <button onclick=\"location.href='view/recruit/recruitWrite.jsp'\" id=\"write\">작성하기</button>\r\n");
      out.write("\t\t   \t\t ");
 } 
      out.write("   \r\n");
      out.write("\t\t   \t\t</div>  \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$('#recruit td').mouseenter(function(){\r\n");
      out.write("\t\t\t\t$(this).parent().css('cursor', 'pointer');\r\n");
      out.write("\t\t\t}).click(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar rNo = $(this).parent().children().eq(0).text();\r\n");
      out.write("\t\t\t\t if('");
      out.print( loginUser );
      out.write("' != 'null'){\r\n");
      out.write("\t\t\t\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/detail.recruit?rNo=' +rNo;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert('로그인 해주세요.');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script> \r\n");
      out.write("\t \r\n");
      out.write("\t<!-- 검색 -->\r\n");
      out.write("\t<br clear=\"left\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"searchDiv\">\r\n");
      out.write("\t<form id=\"searchForm\" action=\"");
      out.print(request.getContextPath() );
      out.write("/list.recruit\" method=\"get\">\r\n");
      out.write("\t\t<select id=\"searchType\" name=\"searchType\">\r\n");
      out.write("\t\t\t<option value=\"all\" selected >전체보기</option>\r\n");
      out.write("\t\t\t<option value=\"netflix\" >NETFLIX</option>\r\n");
      out.write("\t\t\t<option value=\"watcha\" >WATCHA</option>\r\n");
      out.write("\t\t</select>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\r\n");
      out.write("\t\t<input id=\"blank\" type=\"text\" size=\"35\" id=\"searchText\" value=\"\">&nbsp;\r\n");
      out.write("\t\t<input id=\"botSearch\" type=\"button\" value=\"검색\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('#botSearch').click(function(){\r\n");
      out.write("\t\t\tvar choice = $('#searchType').val();\r\n");
      out.write("\t\t\tconsole.log(choice);\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: 'list.recruit',\r\n");
      out.write("\t\t\t\tdata: {choice:choice},\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!— footer —>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br clear=\"all\">\r\n");
      out.write("\r\n");
      out.write("<footer id=\"footer\">\r\n");
      out.write("\t<hr class=\"footer-line\">\r\n");
      out.write("\t<span class=\"f_bottom-contents\">회사소개</span> \r\n");
      out.write("\t<span class=\"f_bottom-contents\"> | 서비스 이용 약관</span>\r\n");
      out.write("\t<span class=\"f_bottom-contents\"> | 개인정보처리방침</span><br> \r\n");
      out.write("\t<img src=\"/Watch_Next/Resources/images/logo.png\" id=\"f_logo\">\r\n");
      out.write("\t<div id=\"copyright\">Copyright 2020. watchnext?. All rights reserved</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/Resources/js/Header.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
