/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-17 06:20:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.recruit;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import recruit.model.vo.*;
import java.util.ArrayList;
import member.model.vo.Member;

public final class recruitDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/view/layout/import.jsp", Long.valueOf(1587052391539L));
    _jspx_dependants.put("/view/layout/footer.jsp", Long.valueOf(1587052391146L));
    _jspx_dependants.put("/view/layout/Header.jsp", Long.valueOf(1587103480562L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("recruit.model.vo");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Recruit r = (Recruit)request.getAttribute("board"); 
	Member m = (Member)request.getAttribute("m");
	ArrayList<Comment> comment = (ArrayList<Comment>)request.getAttribute("comment");
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>모집 글 상세보기</title>\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\"> -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\"> -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css\"> \r\n");
      out.write("<!-- 위에 삭제 해보기 -->\r\n");
      out.write("\r\n");
      out.write("<link type=\"text/css\" href=\"/Watch_Next/Resources/css/hedaer_footer.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link type=\"text/css\" href=\"/Watch_Next/Resources/css/hedaer_footer(AFTER).css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!--페이지에 적용되는 css넣기 -->\r\n");
      out.write("<link rel= \"stylesheet\" type=\"text/css\" href=\"/Watch_Next/Resources/css/a_tag.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css\">\r\n");
      out.write("<link type=\"text/css\" href=\"/Watch_Next/Resources/css/recruit_post.css\" rel=\"stylesheet\" >\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

	Member loginUser = (Member)session.getAttribute("loginUser"); 

      out.write("\r\n");
      out.write("<!-- 헤더 -->\r\n");
      out.write("<header>\r\n");
      out.write("\t<div class=\"nav\">\r\n");
      out.write("\t\t<div class=\"navi_set\">\r\n");
      out.write("\t\t\t<div class=\"topnav\">\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\"><img id=\"logo\" src=\"/Watch_Next/Resources/images/logo.png\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"navi_set\"> \r\n");
      out.write("\t\t\t<div class=\"topnav\">영화</div>\r\n");
      out.write("\t\t\t<ul class=\"subnav\">\r\n");
      out.write("\t\t\t\t<li onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/movie.all'\">정보</li>\r\n");
      out.write("\t\t\t\t<li onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/rec_board.me'\">추천</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"navi_set\">\r\n");
      out.write("\t\t\t<div class=\"topnav\">게시판</div>\r\n");
      out.write("\t\t\t<ul class=\"subnav\">\r\n");
      out.write("\t\t\t\t<li onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/list.rv'\">리뷰 게시판</li>\r\n");
      out.write("\t\t\t\t<li onclick=\"goR();\">모집 게시판</li>\r\n");
      out.write("\t\t\t\t<li>창작 게시판</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"navi_set\">\r\n");
      out.write("\t\t\t<div class=\"topnav\">펀딩</div>\r\n");
      out.write("\t\t\t<ul class=\"subnav\">\r\n");
      out.write("\t\t\t\t<li>수요조사</li>\r\n");
      out.write("\t\t\t\t<li>펀딩참여</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"nav2\">\r\n");
      out.write("\t\t<form autocomplete=\"off\" method=\"post\" id=\"header_action\">\r\n");
      out.write("\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t<div class=\"container-4\">\r\n");
      out.write("\t\t\t\t\t<input type=\"search\" name=\"search\" id=\"search\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"검색어를 입력하세요..\" />\r\n");
      out.write("\t\t\t\t\t<button class=\"icon\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-search\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
 if(loginUser == null) {
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"topnav2\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/Watch_Next/view/pages/loginForm.jsp\" class=\"a_tag\">로그인</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"topnav2\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/Watch_Next/view/pages/JoinForm.jsp\" class=\"a_tag\">회원가입</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t");
 if(loginUser.getAdminYN().equals("N")){
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"topnav2\" id=\"myPage\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/list.all'\">마이 페이지</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
 }else {
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"topnav2\" id=\"myPage\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/view/admin/Admin_myPage.jsp'\">마이 페이지</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"navi_set2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"topnav2\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/logout.me'\">로그아웃</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('.icon').click(function(){\r\n");
      out.write("\t\t\t$(\"#header_action\").attr(\"action\", \"");
      out.print(request.getContextPath());
      out.write("/search.mo?movieTitle=\" + $(\"#search\").val());\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goR(){\r\n");
      out.write("\t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/list.recruit\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<br clear=\"all\">\r\n");
      out.write("\r\n");
      out.write("<br clear=\"all\">\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("\r\n");
      out.write("<!-- 모집 게시판 상세 -->\r\n");
      out.write("\t<div id=\"recruitp\">\r\n");
      out.write("\t\t<h2 style=\"color: white; font-size: 30px;\">모집 게시판글 상세보기</h2>\r\n");
      out.write("\t\t<hr class=\"hline\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"view/recruit/recruitUpdate.jsp\" id=\"detailForm\" name=\"detailForm\">\r\n");
      out.write("\t\t\t<div id=\"box\">\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t\t\t<div id=\"now\">\r\n");
      out.write("\t\t\t\t\t<b>\r\n");
      out.write("\t\t\t\t\t");
      out.print( r.getrHead() );
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print( r.getrHead() );
      out.write("\" name=\"rHead\">\t\r\n");
      out.write("\t\t\t\t\t</b>&nbsp;&nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t<input type=\"text\" readonly=\"");
      out.print( r.getbTitle() );
      out.write("\" id=rctitle name=\"bTitle\" value=\"");
      out.print( r.getbTitle() );
      out.write("\" style=\"border: 0;\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"rNo\" value=\"");
      out.print(r.getrNo() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("  \r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"wInfo\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"850px\" style=\"font-size:17px;\"></td>\r\n");
      out.write("\t\t\t\t<td width=\"90px\" style=\"font-size:17px;\">글쓴이 : </td>\r\n");
      out.write("\t\t\t\t<td width=\"70px\" style=\"font-size:17px;\" id=\"rpWriter\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" readonly=\"");
      out.print(r.getUserId() );
      out.write("\" name=\"userId\" value=\"");
      out.print(r.getUserId());
      out.write("\" style=\"border: 0;\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>쪽지보내기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href='#'>팔로우하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"70px\" style=\"font-size:17px;\">날짜 : </td>\r\n");
      out.write("\t\t      \t<td width=\"150px\" style=\"font-size:17px;\" >\r\n");
      out.write("\t\t      \t\t<input type=\"text\" readonly=\"");
      out.print(r.getbDate() );
      out.write("\" name=\"bDate\" value=\"");
      out.print(r.getbDate());
      out.write("\" style=\"border: 0;\">\r\n");
      out.write("\t\t      \t</td>\r\n");
      out.write("\t\t      \t<td width=\"90px\" style=\"font-size:17px;\">조회수 : </td>\r\n");
      out.write("\t\t      \t<td width=\"70px\" style=\"font-size:17px;\" >\r\n");
      out.write("\t\t      \t\t<input type=\"text\" readonly=\"");
      out.print(r.getbViews() );
      out.write("\" name=\"bViews\"\tvalue=\"");
      out.print( r.getbViews() );
      out.write("\" style=\"border:0;\">\r\n");
      out.write("\t\t      \t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t\t<p style=\"font-size:15px;\" >\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"bContent\" value=\"");
      out.print(r.getbContent() );
      out.write("\" style=\"border:0;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 신고버튼 -->\r\n");
      out.write("\t<div id=\"btn\">\r\n");
      out.write("\t\t<button  >\r\n");
      out.write("\t\t\t<img src=\"/Watch_Next/Resources/images/siren2.png\" width=\"37px\" height=\"37px\"\r\n");
      out.write("\t\t\t\tonclick=\"window.open('/Watch_Next/view/reportPop/reportPop.jsp', 'pop', \r\n");
      out.write("\t\t\t\t'left'='+(screen.availWidth-500)/2+','top='+'(screen.availHeight-300)/2+', 'width=500px','height=300px')\">\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t    <!-- 목록수정삭제 버튼 -->\r\n");
      out.write(" \r\n");
      out.write("\t\t<div id=listbtn>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t    ");
 if(loginUser != null && loginUser.getUserId().equals(r.getUserId())) { 
      out.write("\r\n");
      out.write("\t\t    \t<button type=\"submit\" id=\"update\" value=\"수정\">수정</button>\r\n");
      out.write("\t\t    \t<button type=\"button\" id=\"delete\" onclick=\"deleteRe();\" value=\"삭제\">삭제</button>\r\n");
      out.write("\t\t   ");
 } 
      out.write("\r\n");
      out.write("\t\t    \t<div onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/list.recruit'\" id=\"menu\"\r\n");
      out.write("\t\t    \t\tstyle=\"background-color:red; color:white;\r\n");
      out.write("\t\t\t\tborder:none; border-radius:5px; \r\n");
      out.write("\t\t\t\twidth:50px; height:25px; font-size:14px; text-align:center;\" >목록</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \t<!-- 댓글 -->\r\n");
      out.write("\t<div id=\"replybox1\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<textarea id=\"reply_content\" name=\"reply_content\" rows=\"2\" cols=\"167\"  \r\n");
      out.write("\t\t\t\t  placeholder=\"댓글을 입력하세요.\" ></textarea>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<button id=\"reply_save\">댓글 작성</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<br clear=\"all\">\r\n");
      out.write("\t<div id=\"replybox2\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t");
 if(comment.isEmpty()) { 
      out.write("\r\n");
      out.write("\t\t\t\t<tr><td colspan=3 style=\"font-size:14px; text-align:center\">댓글이 없습니다.</td></tr>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t\t");
 for(int i = 0; i < comment.size(); i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>");
      out.print( comment.get(i).getrWriter() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t");
 if(loginUser != null && loginUser.getUserId().equals(comment.get(i).getrWriter())) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" id=\"deleteComment\" onclick=\"dCo();\" style=\"margin-top:10px; margin-left:90%; background-color:red; color:white; \r\n");
      out.write("\t\t\t\t\t\t\t\tfont-size:13px; border:none; border-radius:5px;\">삭제</button>\r\n");
      out.write("\t\t\t\t\t\t");
 } else {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<button type=button id=report onclick=\"window.open('");
      out.print(request.getContextPath() );
      out.write("/view/reportPop/reportPop.jsp', 'pop', \r\n");
      out.write("\t\t\t\t\t\t\t'left='+(screen.availWidth-500)/2+',top='+(screen.availHeight-300)/2+', width=500px,height=300px')\">신고</button>\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\t\r\n");
      out.write("\t\t\t\t\t<td colspan=2 style=\"font-size:14px\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( comment.get(i).getrContent() );
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\tfunction deleteRe(){\r\n");
      out.write("\t\t\t\tvar d = confirm('게시글을 삭제하시겠습니까?');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(d){\r\n");
      out.write("\t\t\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath() );
      out.write("/delete.recruit?rNo=\" + ");
      out.print(r.getrNo() );
      out.write(";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction dCo(){\r\n");
      out.write("\t\t\t\tvar de = confirm('댓글을 삭제하시겠습니까?');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(de){\r\n");
      out.write("\t\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath() );
      out.write("/delete.comment\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t$('#reply_save').click(function(){\r\n");
      out.write("\t\t\t\tvar writer = '");
      out.print( loginUser.getUserId() );
      out.write("';\r\n");
      out.write("\t\t\t\tvar rNo = '");
      out.print( r.getrNo() );
      out.write("';\r\n");
      out.write("\t\t\t\tvar content = $('#reply_content').val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif($('#reply_content').val(); == null){\r\n");
      out.write("\t\t\t\t\talert(\"댓글을 작성해주세요\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"댓글 작성 완료\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : 'insertComment.recruit',\r\n");
      out.write("\t\t\t\t\tdata : {writer:writer, content:content, rNo:rNo},\r\n");
      out.write("\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\t$replyTable = $('#replySelectTable');\r\n");
      out.write("\t\t\t\t\t\t$replyTable.text(\"\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tfor(var key in data){\r\n");
      out.write("\t\t\t\t\t\t\tvar $tr = $('<tr>');\r\n");
      out.write("\t\t\t\t\t\t\tvar $writerTd = $('<td>').text(data[key].rWriter).css('color','red');\r\n");
      out.write("\t\t\t\t\t\t\tvar $contentTd = $('<td>').text(data[key].rContent).css('font-size','14px');\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$tr.append($writerTd);\r\n");
      out.write("\t\t\t\t\t\t\t$tr.append($contentTd);\r\n");
      out.write("\t\t\t\t\t\t\t$replyTable.append($tr);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$('#reply_content').val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#replySelectTable\").load(window.location.href + \" #replySelectTable\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("<!— footer —>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br clear=\"all\">\r\n");
      out.write("\r\n");
      out.write("<footer id=\"footer\">\r\n");
      out.write("\t<hr class=\"footer-line\">\r\n");
      out.write("\t<span class=\"f_bottom-contents\">회사소개</span> \r\n");
      out.write("\t<span class=\"f_bottom-contents\"> | 서비스 이용 약관</span>\r\n");
      out.write("\t<span class=\"f_bottom-contents\"> | 개인정보처리방침</span><br> \r\n");
      out.write("\t<img src=\"/Watch_Next/Resources/images/logo.png\" id=\"f_logo\">\r\n");
      out.write("\t<div id=\"copyright\">Copyright 2020. watchnext?. All rights reserved</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/Resources/js/Header.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
