/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-09 10:40:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\tbody{background: beige;}\r\n");
      out.write("\t.test{width: 300px; min-height: 50px; border: 1px solid red;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>jQuery를 통한 Ajax 구현</h1>\r\n");
      out.write("\t\r\n");
      out.write("\t<h3>1. 버튼 선택 시 전송 값 서버에 출력</h3>\r\n");
      out.write("\t이름 : <input type=\"text\" id=\"myName\">\r\n");
      out.write("\t<button id=\"nameBtn\">이름 전송</button>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('#nameBtn').click(function(){\r\n");
      out.write("\t\t\tvar name = $('#myName').val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : 'jQueryTest1.do',\r\n");
      out.write("\t\t\t\tdata : {name:name},\r\n");
      out.write("\t\t\t\ttype : 'post',\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\tconsole.log('서버 성공 시 호출되는 함수');\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log('서버 전송 실패시 호출되는 함수');\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tcomplete: function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log('성공 여부에 상관 없이 무조건 호출되는 함수');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t<h3>2. 버튼 선택 시 서버에서 보낸 값 사용자가 수신</h3>\r\n");
      out.write("\t<button id=\"getServerTextBtn\">서버에서 보낸 값 확인</button>\r\n");
      out.write("\t<p class=\"test\" id=\"p1\"></p>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('#getServerTextBtn').click(function(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"jQueryTest2.do\",\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t$('#p1').text(data);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t<h3>3. 서버로 기본형 전송 값이 있고 결과로 문자열을 받아 처리</h3>\r\n");
      out.write("\t<h4>두 개의 값을 더한 결과를 받아옴</h4>\r\n");
      out.write("\t첫번째 숫자 : <input type=\"text\" id=\"firstNum\"><br>\r\n");
      out.write("\t두번째 숫자 : <input type=\"text\" id=\"secondNum\"><br>\r\n");
      out.write("\t<button id=\"plusBtn\">더하기</button>\r\n");
      out.write("\t<p class=\"test\" id=\"p2\"></p>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//jQueryTest3.do에 위 두개의 값 전송\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#plusBtn').click(function(){\r\n");
      out.write("\t\t\tvar firstNum = $('#firstNum').val();\r\n");
      out.write("\t\t\tvar secondNum = $('#secondNum').val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : 'jQueryTest3.do',\r\n");
      out.write("\t\t\t\tdata : {firstNum:firstNum, secondNum:secondNum},\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t$('#p2').text(data);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<h3>4. Object형태의 데이터를 서버에 전송, 서버에서 처리 후 서버 console로 출력</h3>\r\n");
      out.write("\t학생 1 : <input type=\"text\" id=\"student1\"><br>\r\n");
      out.write("\t학생 2 : <input type=\"text\" id=\"student2\"><br>\r\n");
      out.write("\t학생 3 : <input type=\"text\" id=\"student3\"><br>\r\n");
      out.write("\t<button id=\"studentTest\">결과 확인</button>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('#studentTest').click(function(){\r\n");
      out.write("\t\t\tvar student1 = $('#student1').val();\r\n");
      out.write("\t\t\tvar student2 = $('#student2').val();\r\n");
      out.write("\t\t\tvar student3 = $('#student3').val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar students = {student1:student1, student2:student2, student3:student3};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"jQueryTest4.do\",\r\n");
      out.write("\t\t\t\tdata : students\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t<h3>5. 서버로 기본형 데이터 전송, 서버에서 객체 반환</h3>\r\n");
      out.write("\t<h4>유저 번호 보내서 해당 유저 정보 가져오기</h4>\r\n");
      out.write("\t유저번호 : <input type=\"text\" id=\"userNo\"><br>\r\n");
      out.write("\t<button id=\"getUserInfoBtn\">정보 가져오기</button>\r\n");
      out.write("\t<p class=\"test\" id=\"p3\"></p>\r\n");
      out.write("\t<textarea class=\"text\" id=\"textarea3\" cols=40 rows=5></textarea>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('#getUserInfoBtn').click(function(){\r\n");
      out.write("\t\t\tvar userNo = $('#userNo').val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : 'jQueryTest5.do',\r\n");
      out.write("\t\t\t\tdata : {userNo:userNo},\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar resultStr = \"\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(data != null){\r\n");
      out.write("\t\t\t\t\t\tresultStr = data.userNo + \", \" + data.userName + \", \" + data.userNation;\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tresultStr = \"해당회원이 없습니다.\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('#p3').text(resultStr);\r\n");
      out.write("\t\t\t\t\t$('#textarea3').val(resultStr);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<h3>6. 서버로 기본 값 전송, 서버에서 리스트 객체 반환</h3>\r\n");
      out.write("\t<h4>유저 번호 요청 ---> 해당 유저가 있는 경우 유저 정보, 없는 경우 전체 가져오기</h4>\r\n");
      out.write("\t유저 번호 : <input type=\"text\" id=\"userNo2\"><br>\r\n");
      out.write("\t<button id=\"getUserInfoBtn2\">정보 가져오기</button>\r\n");
      out.write("\t<p class=\"test\" id=\"p4\"></p>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('#getUserInfoBtn2').click(function(){\r\n");
      out.write("\t\t\tvar userNo = $('#userNo2').val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : 'jQueryTest6.do',\r\n");
      out.write("\t\t\t\tdata : {userNo:userNo},\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar resultStr = \"\";\r\n");
      out.write("\t\t\t\t\tfor(var i in data){\r\n");
      out.write("\t\t\t\t\t\tvar user = data[i];\r\n");
      out.write("\t\t\t\t\t\tconsole.log(user);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tresultStr += user.userNo + \", \" + user.userName + \", \" + user.userNation ;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('#p4').text(resultStr);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<h3>7. 서버로 데이터 여러개 전송, 서버에서 리스트 객체 반환</h3>\r\n");
      out.write("\t<h4>유저 번호 전송 ---> 현재 있는 유저 정보만 모아서 출력</h4>\r\n");
      out.write("\t<h4>10이상의 숫자는 ','로 쓸 수 없다고 가정</h4>\r\n");
      out.write("\t유저 정보(번호, 번호, 번호) : <input type=\"text\" id=\"userNo3\"><br>\r\n");
      out.write("\t<button id=\"getUserInfoBtn3\">정보 가져오기</button>\r\n");
      out.write("\t<textarea class=\"test\" id=\"textarea5\" cols=40 rows=5></textarea>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('#getUserInfoBtn3').click(function(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : 'jQueryTest7.do',\r\n");
      out.write("\t\t\t\tdata : {userNo3:$('#userNo3').val()},\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar Str = \"\";\r\n");
      out.write("\t\t\t\t\tfor(var i in data){\r\n");
      out.write("\t\t\t\t\t\tvar user = data[i];\r\n");
      out.write("\t\t\t\t\t\tStr += user.userNo + \", \" + user.userName + \", \" + user.userNation + \"\\n\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('#textarea5').val(Str);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<h3>8. 서버로 데이터 여러 개 전송, 서버에서 맵 형태의 객체 반환</h3>\r\n");
      out.write("\t<h4>유저 이름 전송 ----> 현재 있는 유저 정보만 모아서 출력</h4>\r\n");
      out.write("\t유저 정보(이름, 이름, 이름) : <input type=\"text\" id=\"userName\"><br>\r\n");
      out.write("\t<button id=\"getUserInfoBtn4\">정보 가져오기</button>\r\n");
      out.write("\t<textarea rows=5 cols=40 id=\"textarea6\" class=\"test\"></textarea>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$('#getUserInfoBtn4').click(function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : 'jQueryTest8.do',\r\n");
      out.write("\t\t\tdata : {userName:$('#userName').val()},\r\n");
      out.write("\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\t\tfor(var key in data){\r\n");
      out.write("\t\t\t\t\tvar user = data[key];\r\n");
      out.write("\t\t\t\t\tconsole.log(user);\r\n");
      out.write("\t\t\t\t\tstr += user.userNo + \", \" + user.userName + \", \" + user.userNation + \"\\n\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#textarea6').val(str);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<h3>9. 서버 유저 정보로 표 구성하기</h3>\r\n");
      out.write("\t<button id=\"userInfoBtn\">유저 정보 불러오기</button>\r\n");
      out.write("\t<table id=\"userInfoTable\" border=\"1\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t<th>국적</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody></tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('#userInfoBtn').click(function(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"jQueryTest9.do\",\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$tableBody = $('#userInfoTable tbody');\t\t//jQuery로 만든 객체라는 뜻의 $. \r\n");
      out.write("\t\t\t\t\t$tableBody.html(\"\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var i in data){\r\n");
      out.write("\t\t\t\t\t\tvar $tr = $(\"<tr>\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar $noTd = $(\"<td>\").text(data[i].userNo);\r\n");
      out.write("\t\t\t\t\t\tvar $nameTd = $(\"<td>\").text(data[i].userName);\r\n");
      out.write("\t\t\t\t\t\tvar $nationTd = $(\"<td>\").text(data[i].userNation);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$tr.append($noTd);\r\n");
      out.write("\t\t\t\t\t\t$tr.append($nameTd);\r\n");
      out.write("\t\t\t\t\t\t$tr.append($nationTd);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$tableBody.append($tr);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<h3>10. 서버에서 List객체 반환 받아 select태그를 이용해서 보여줌</h3>\r\n");
      out.write("\t유저 이름 : <input type=\"text\" id=\"selectUserName\">\r\n");
      out.write("\t<button id=\"selectListBtn\">예제</button><br>\r\n");
      out.write("\t<select id=\"selectListTest\"></select>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('#selectListBtn').click(function(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : 'jQueryTest10.do',\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$select = $(\"#selectListTest\");\r\n");
      out.write("\t\t\t\t\t$select.find('option').remove();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < data.length; i++){\r\n");
      out.write("\t\t\t\t\t\tvar name = data[i].userName;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar selected = (name == $('#selectUserName').val()) ? 'selected' : '';\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$select.append('<option value=\"' + data[i].userNo + '\"' + selected + \">\" + name + \"</option>\");\r\n");
      out.write("\t\t\t\t\t\t//<option value=\"1\" selected>박신우</option>\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<h3>11. Gson을 이용한 List반환</h3>\r\n");
      out.write("\t<button id=\"gsonList\">list 가져오기</button>\r\n");
      out.write("\t<select id=\"gsonListSelect\"></select>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(\"#gsonList\").click(function(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : 'jQueryTest11.do',\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$select = $('#gsonListSelect');\r\n");
      out.write("\t\t\t\t\t$select.find('option').remove();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var i in data){\r\n");
      out.write("\t\t\t\t\t\tvar $option = $('<option>');\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$option.val(data[i].userNo);\r\n");
      out.write("\t\t\t\t\t\t$option.text(data[i].userName);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$select.append($option);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<h3>12. Gson을 이용한 Map반환</h3>\r\n");
      out.write("\t<button id=\"gsonMapBtn\">Map 가져오기</button>\r\n");
      out.write("\t<select id=\"gsonMapSelect\"></select>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('#gsonMapBtn').click(function(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : 'jQueryTest12.do',\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$select = $('#gsonMapSelect');\r\n");
      out.write("\t\t\t\t\t$select.find('option').remove();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var i in data){\r\n");
      out.write("\t\t\t\t\t\tvar $option = $('<option>');\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$option.val(data[i].userNo);\r\n");
      out.write("\t\t\t\t\t\t$option.text(data[i].userName);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$select.append($option);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
